# Generated by Django 3.1.3 on 2020-11-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20201106_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='circles',
            new_name='circle',
        ),
    ]
